# Generated by Django 5.1 on 2024-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
                ('response', models.JSONField()),
                ('params', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
